System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "stage": 0,
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    "dist/bundle.js": [
      "app.js",
      "npm:react-router@1.0.1.js",
      "npm:react-router@1.0.1/lib/index.js",
      "npm:react-router@1.0.1/lib/match.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "npm:process@0.11.2.js",
      "npm:process@0.11.2/browser.js",
      "npm:react-router@1.0.1/lib/useRoutes.js",
      "npm:react-router@1.0.1/lib/matchRoutes.js",
      "npm:react-router@1.0.1/lib/RouteUtils.js",
      "npm:warning@2.1.0.js",
      "npm:warning@2.1.0/browser.js",
      "npm:react@0.14.3.js",
      "npm:react@0.14.3/react.js",
      "npm:react@0.14.3/lib/React.js",
      "npm:react@0.14.3/lib/deprecated.js",
      "npm:fbjs@0.3.2/lib/warning.js",
      "npm:fbjs@0.3.2/lib/emptyFunction.js",
      "npm:react@0.14.3/lib/Object.assign.js",
      "npm:react@0.14.3/lib/ReactIsomorphic.js",
      "npm:react@0.14.3/lib/onlyChild.js",
      "npm:fbjs@0.3.2/lib/invariant.js",
      "npm:react@0.14.3/lib/ReactElement.js",
      "npm:react@0.14.3/lib/canDefineProperty.js",
      "npm:react@0.14.3/lib/ReactCurrentOwner.js",
      "npm:react@0.14.3/lib/ReactVersion.js",
      "npm:react@0.14.3/lib/ReactPropTypes.js",
      "npm:react@0.14.3/lib/getIteratorFn.js",
      "npm:react@0.14.3/lib/ReactPropTypeLocationNames.js",
      "npm:react@0.14.3/lib/ReactElementValidator.js",
      "npm:react@0.14.3/lib/ReactPropTypeLocations.js",
      "npm:fbjs@0.3.2/lib/keyMirror.js",
      "npm:react@0.14.3/lib/ReactDOMFactories.js",
      "npm:fbjs@0.3.2/lib/mapObject.js",
      "npm:react@0.14.3/lib/ReactClass.js",
      "npm:fbjs@0.3.2/lib/keyOf.js",
      "npm:fbjs@0.3.2/lib/emptyObject.js",
      "npm:react@0.14.3/lib/ReactNoopUpdateQueue.js",
      "npm:react@0.14.3/lib/ReactComponent.js",
      "npm:react@0.14.3/lib/ReactChildren.js",
      "npm:react@0.14.3/lib/traverseAllChildren.js",
      "npm:react@0.14.3/lib/ReactInstanceHandles.js",
      "npm:react@0.14.3/lib/ReactRootIndex.js",
      "npm:react@0.14.3/lib/PooledClass.js",
      "npm:react@0.14.3/lib/ReactDOMServer.js",
      "npm:react@0.14.3/lib/ReactServerRendering.js",
      "npm:react@0.14.3/lib/instantiateReactComponent.js",
      "npm:react@0.14.3/lib/ReactNativeComponent.js",
      "npm:react@0.14.3/lib/ReactEmptyComponent.js",
      "npm:react@0.14.3/lib/ReactReconciler.js",
      "npm:react@0.14.3/lib/ReactRef.js",
      "npm:react@0.14.3/lib/ReactOwner.js",
      "npm:react@0.14.3/lib/ReactEmptyComponentRegistry.js",
      "npm:react@0.14.3/lib/ReactCompositeComponent.js",
      "npm:react@0.14.3/lib/shouldUpdateReactComponent.js",
      "npm:react@0.14.3/lib/ReactUpdateQueue.js",
      "npm:react@0.14.3/lib/ReactUpdates.js",
      "npm:react@0.14.3/lib/Transaction.js",
      "npm:react@0.14.3/lib/ReactPerf.js",
      "npm:react@0.14.3/lib/CallbackQueue.js",
      "npm:react@0.14.3/lib/ReactInstanceMap.js",
      "npm:react@0.14.3/lib/ReactComponentEnvironment.js",
      "npm:react@0.14.3/lib/ReactServerRenderingTransaction.js",
      "npm:react@0.14.3/lib/ReactServerBatchingStrategy.js",
      "npm:react@0.14.3/lib/ReactMarkupChecksum.js",
      "npm:react@0.14.3/lib/adler32.js",
      "npm:react@0.14.3/lib/ReactDefaultBatchingStrategy.js",
      "npm:react@0.14.3/lib/ReactDefaultInjection.js",
      "npm:react@0.14.3/lib/ReactDefaultPerf.js",
      "npm:fbjs@0.3.2/lib/performanceNow.js",
      "npm:fbjs@0.3.2/lib/performance.js",
      "npm:fbjs@0.3.2/lib/ExecutionEnvironment.js",
      "npm:react@0.14.3/lib/ReactMount.js",
      "npm:react@0.14.3/lib/validateDOMNesting.js",
      "npm:react@0.14.3/lib/setInnerHTML.js",
      "npm:fbjs@0.3.2/lib/containsNode.js",
      "npm:fbjs@0.3.2/lib/isTextNode.js",
      "npm:fbjs@0.3.2/lib/isNode.js",
      "npm:react@0.14.3/lib/ReactDOMFeatureFlags.js",
      "npm:react@0.14.3/lib/ReactBrowserEventEmitter.js",
      "npm:react@0.14.3/lib/isEventSupported.js",
      "npm:react@0.14.3/lib/ViewportMetrics.js",
      "npm:react@0.14.3/lib/ReactEventEmitterMixin.js",
      "npm:react@0.14.3/lib/EventPluginHub.js",
      "npm:react@0.14.3/lib/forEachAccumulated.js",
      "npm:react@0.14.3/lib/accumulateInto.js",
      "npm:react@0.14.3/lib/ReactErrorUtils.js",
      "npm:react@0.14.3/lib/EventPluginUtils.js",
      "npm:react@0.14.3/lib/EventConstants.js",
      "npm:react@0.14.3/lib/EventPluginRegistry.js",
      "npm:react@0.14.3/lib/DOMProperty.js",
      "npm:react@0.14.3/lib/ReactDefaultPerfAnalysis.js",
      "npm:react@0.14.3/lib/SVGDOMPropertyConfig.js",
      "npm:react@0.14.3/lib/SimpleEventPlugin.js",
      "npm:react@0.14.3/lib/getEventCharCode.js",
      "npm:react@0.14.3/lib/SyntheticWheelEvent.js",
      "npm:react@0.14.3/lib/SyntheticMouseEvent.js",
      "npm:react@0.14.3/lib/getEventModifierState.js",
      "npm:react@0.14.3/lib/SyntheticUIEvent.js",
      "npm:react@0.14.3/lib/getEventTarget.js",
      "npm:react@0.14.3/lib/SyntheticEvent.js",
      "npm:react@0.14.3/lib/SyntheticTouchEvent.js",
      "npm:react@0.14.3/lib/SyntheticDragEvent.js",
      "npm:react@0.14.3/lib/SyntheticKeyboardEvent.js",
      "npm:react@0.14.3/lib/getEventKey.js",
      "npm:react@0.14.3/lib/SyntheticFocusEvent.js",
      "npm:react@0.14.3/lib/SyntheticClipboardEvent.js",
      "npm:react@0.14.3/lib/EventPropagators.js",
      "npm:fbjs@0.3.2/lib/EventListener.js",
      "npm:react@0.14.3/lib/ServerReactRootIndex.js",
      "npm:react@0.14.3/lib/SelectEventPlugin.js",
      "npm:fbjs@0.3.2/lib/shallowEqual.js",
      "npm:react@0.14.3/lib/isTextInputElement.js",
      "npm:fbjs@0.3.2/lib/getActiveElement.js",
      "npm:react@0.14.3/lib/ReactInputSelection.js",
      "npm:fbjs@0.3.2/lib/focusNode.js",
      "npm:react@0.14.3/lib/ReactDOMSelection.js",
      "npm:react@0.14.3/lib/getTextContentAccessor.js",
      "npm:react@0.14.3/lib/getNodeForCharacterOffset.js",
      "npm:react@0.14.3/lib/ReactReconcileTransaction.js",
      "npm:react@0.14.3/lib/ReactInjection.js",
      "npm:react@0.14.3/lib/ReactEventListener.js",
      "npm:fbjs@0.3.2/lib/getUnboundedScrollPosition.js",
      "npm:react@0.14.3/lib/ReactDOMTextComponent.js",
      "npm:react@0.14.3/lib/setTextContent.js",
      "npm:react@0.14.3/lib/escapeTextContentForBrowser.js",
      "npm:react@0.14.3/lib/ReactComponentBrowserEnvironment.js",
      "npm:react@0.14.3/lib/ReactDOMIDOperations.js",
      "npm:react@0.14.3/lib/DOMPropertyOperations.js",
      "npm:react@0.14.3/lib/quoteAttributeValueForBrowser.js",
      "npm:react@0.14.3/lib/DOMChildrenOperations.js",
      "npm:react@0.14.3/lib/ReactMultiChildUpdateTypes.js",
      "npm:react@0.14.3/lib/Danger.js",
      "npm:fbjs@0.3.2/lib/getMarkupWrap.js",
      "npm:fbjs@0.3.2/lib/createNodesFromMarkup.js",
      "npm:fbjs@0.3.2/lib/createArrayFromMixed.js",
      "npm:fbjs@0.3.2/lib/toArray.js",
      "npm:react@0.14.3/lib/ReactDOMComponent.js",
      "npm:react@0.14.3/lib/ReactMultiChild.js",
      "npm:react@0.14.3/lib/flattenChildren.js",
      "npm:react@0.14.3/lib/ReactChildReconciler.js",
      "npm:react@0.14.3/lib/ReactDOMTextarea.js",
      "npm:react@0.14.3/lib/LinkedValueUtils.js",
      "npm:react@0.14.3/lib/ReactDOMSelect.js",
      "npm:react@0.14.3/lib/ReactDOMOption.js",
      "npm:react@0.14.3/lib/ReactDOMInput.js",
      "npm:react@0.14.3/lib/ReactDOMButton.js",
      "npm:react@0.14.3/lib/CSSPropertyOperations.js",
      "npm:fbjs@0.3.2/lib/memoizeStringOnly.js",
      "npm:fbjs@0.3.2/lib/hyphenateStyleName.js",
      "npm:fbjs@0.3.2/lib/hyphenate.js",
      "npm:react@0.14.3/lib/dangerousStyleValue.js",
      "npm:react@0.14.3/lib/CSSProperty.js",
      "npm:fbjs@0.3.2/lib/camelizeStyleName.js",
      "npm:fbjs@0.3.2/lib/camelize.js",
      "npm:react@0.14.3/lib/AutoFocusUtils.js",
      "npm:react@0.14.3/lib/findDOMNode.js",
      "npm:react@0.14.3/lib/ReactBrowserComponentMixin.js",
      "npm:react@0.14.3/lib/HTMLDOMPropertyConfig.js",
      "npm:react@0.14.3/lib/EnterLeaveEventPlugin.js",
      "npm:react@0.14.3/lib/DefaultEventPluginOrder.js",
      "npm:react@0.14.3/lib/ClientReactRootIndex.js",
      "npm:react@0.14.3/lib/ChangeEventPlugin.js",
      "npm:react@0.14.3/lib/BeforeInputEventPlugin.js",
      "npm:react@0.14.3/lib/SyntheticInputEvent.js",
      "npm:react@0.14.3/lib/SyntheticCompositionEvent.js",
      "npm:react@0.14.3/lib/FallbackCompositionState.js",
      "npm:react@0.14.3/lib/ReactDOM.js",
      "npm:react@0.14.3/lib/renderSubtreeIntoContainer.js",
      "npm:react-router@1.0.1/lib/PatternUtils.js",
      "npm:invariant@2.2.0.js",
      "npm:invariant@2.2.0/browser.js",
      "npm:react-router@1.0.1/lib/AsyncUtils.js",
      "npm:react-router@1.0.1/lib/getComponents.js",
      "npm:react-router@1.0.1/lib/isActive.js",
      "npm:react-router@1.0.1/lib/TransitionUtils.js",
      "npm:react-router@1.0.1/lib/computeChangedRoutes.js",
      "npm:history@1.13.1/lib/useQueries.js",
      "npm:history@1.13.1/lib/parsePath.js",
      "npm:history@1.13.1/lib/extractPath.js",
      "npm:history@1.13.1/lib/runTransitionHook.js",
      "npm:qs@4.0.0.js",
      "npm:qs@4.0.0/lib/index.js",
      "npm:qs@4.0.0/lib/parse.js",
      "npm:qs@4.0.0/lib/utils.js",
      "npm:qs@4.0.0/lib/stringify.js",
      "npm:history@1.13.1/lib/Actions.js",
      "npm:history@1.13.1/lib/useBasename.js",
      "npm:history@1.13.1/lib/ExecutionEnvironment.js",
      "npm:history@1.13.1/lib/createMemoryHistory.js",
      "npm:history@1.13.1/lib/createHistory.js",
      "npm:history@1.13.1/lib/deprecate.js",
      "npm:history@1.13.1/lib/createLocation.js",
      "npm:history@1.13.1/lib/AsyncUtils.js",
      "npm:deep-equal@1.0.1.js",
      "npm:deep-equal@1.0.1/index.js",
      "npm:deep-equal@1.0.1/lib/is_arguments.js",
      "npm:deep-equal@1.0.1/lib/keys.js",
      "npm:react-router@1.0.1/lib/PropTypes.js",
      "npm:react-router@1.0.1/lib/RoutingContext.js",
      "npm:react-router@1.0.1/lib/getRouteParams.js",
      "npm:react-router@1.0.1/lib/RouteContext.js",
      "npm:react-router@1.0.1/lib/Lifecycle.js",
      "npm:react-router@1.0.1/lib/History.js",
      "npm:react-router@1.0.1/lib/Route.js",
      "npm:react-router@1.0.1/lib/Redirect.js",
      "npm:react-router@1.0.1/lib/IndexRoute.js",
      "npm:react-router@1.0.1/lib/IndexRedirect.js",
      "npm:react-router@1.0.1/lib/IndexLink.js",
      "npm:react-router@1.0.1/lib/Link.js",
      "npm:react-router@1.0.1/lib/Router.js",
      "npm:history@1.13.1/lib/createHashHistory.js",
      "npm:history@1.13.1/lib/createDOMHistory.js",
      "npm:history@1.13.1/lib/DOMUtils.js",
      "npm:history@1.13.1/lib/DOMStateStorage.js",
      "npm:react-dom@0.14.3.js",
      "npm:react-dom@0.14.3/index.js",
      "components/acme_footer/acme-footer.js",
      "npm:babel-runtime@5.8.34/helpers/class-call-check.js",
      "npm:babel-runtime@5.8.34/helpers/create-class.js",
      "npm:babel-runtime@5.8.34/core-js/object/define-property.js",
      "npm:core-js@1.2.6/library/fn/object/define-property.js",
      "npm:core-js@1.2.6/library/modules/$.js",
      "npm:babel-runtime@5.8.34/helpers/inherits.js",
      "npm:babel-runtime@5.8.34/core-js/object/set-prototype-of.js",
      "npm:core-js@1.2.6/library/fn/object/set-prototype-of.js",
      "npm:core-js@1.2.6/library/modules/$.core.js",
      "npm:core-js@1.2.6/library/modules/es6.object.set-prototype-of.js",
      "npm:core-js@1.2.6/library/modules/$.set-proto.js",
      "npm:core-js@1.2.6/library/modules/$.ctx.js",
      "npm:core-js@1.2.6/library/modules/$.a-function.js",
      "npm:core-js@1.2.6/library/modules/$.an-object.js",
      "npm:core-js@1.2.6/library/modules/$.is-object.js",
      "npm:core-js@1.2.6/library/modules/$.export.js",
      "npm:core-js@1.2.6/library/modules/$.global.js",
      "npm:babel-runtime@5.8.34/core-js/object/create.js",
      "npm:core-js@1.2.6/library/fn/object/create.js",
      "npm:babel-runtime@5.8.34/helpers/get.js",
      "npm:babel-runtime@5.8.34/core-js/object/get-own-property-descriptor.js",
      "npm:core-js@1.2.6/library/fn/object/get-own-property-descriptor.js",
      "npm:core-js@1.2.6/library/modules/es6.object.get-own-property-descriptor.js",
      "npm:core-js@1.2.6/library/modules/$.object-sap.js",
      "npm:core-js@1.2.6/library/modules/$.fails.js",
      "npm:core-js@1.2.6/library/modules/$.to-iobject.js",
      "npm:core-js@1.2.6/library/modules/$.defined.js",
      "npm:core-js@1.2.6/library/modules/$.iobject.js",
      "npm:core-js@1.2.6/library/modules/$.cof.js",
      "components/acme_body/acme-body.js",
      "components/acme_body/acme_list_group/acme-list-group.js",
      "npm:react-router-bootstrap@0.19.3.js",
      "npm:react-router-bootstrap@0.19.3/lib/index.js",
      "npm:react-router-bootstrap@0.19.3/lib/LinkContainer.js",
      "npm:react-router-bootstrap@0.19.3/lib/IndexLinkContainer.js",
      "npm:react-bootstrap@0.28.1.js",
      "npm:react-bootstrap@0.28.1/lib/index.js",
      "npm:react-bootstrap@0.28.1/lib/FormControls/index.js",
      "npm:react-bootstrap@0.28.1/lib/FormControls/Static.js",
      "npm:react-bootstrap@0.28.1/lib/utils/childrenValueInputValidation.js",
      "npm:react-prop-types@0.3.0/lib/singlePropFrom.js",
      "npm:babel-runtime@5.8.34/helpers/interop-require-default.js",
      "npm:react-bootstrap@0.28.1/lib/InputBase.js",
      "npm:react-bootstrap@0.28.1/lib/Glyphicon.js",
      "npm:classnames@2.2.1.js",
      "npm:classnames@2.2.1/index.js",
      "npm:babel-runtime@5.8.34/helpers/extends.js",
      "npm:babel-runtime@5.8.34/core-js/object/assign.js",
      "npm:core-js@1.2.6/library/fn/object/assign.js",
      "npm:core-js@1.2.6/library/modules/es6.object.assign.js",
      "npm:core-js@1.2.6/library/modules/$.object-assign.js",
      "npm:core-js@1.2.6/library/modules/$.to-object.js",
      "npm:react-bootstrap@0.28.1/lib/FormGroup.js",
      "npm:react-bootstrap@0.28.1/lib/Fade.js",
      "npm:react-prop-types@0.3.0/lib/deprecated.js",
      "npm:react-overlays@0.5.4/lib/Transition.js",
      "npm:dom-helpers@2.4.0/events/on.js",
      "npm:dom-helpers@2.4.0/util/inDOM.js",
      "npm:dom-helpers@2.4.0/transition/properties.js",
      "npm:react-bootstrap@0.28.1/lib/Collapse.js",
      "npm:react-bootstrap@0.28.1/lib/utils/createChainedFunction.js",
      "npm:dom-helpers@2.4.0/style.js",
      "npm:dom-helpers@2.4.0/style/index.js",
      "npm:dom-helpers@2.4.0/style/removeStyle.js",
      "npm:dom-helpers@2.4.0/style/getComputedStyle.js",
      "npm:dom-helpers@2.4.0/util/camelizeStyle.js",
      "npm:dom-helpers@2.4.0/util/camelize.js",
      "npm:dom-helpers@2.4.0/util/babelHelpers.js",
      "npm:dom-helpers@2.4.0/util/hyphenateStyle.js",
      "npm:dom-helpers@2.4.0/util/hyphenate.js",
      "npm:react-bootstrap@0.28.1/lib/Well.js",
      "npm:react-bootstrap@0.28.1/lib/styleMaps.js",
      "npm:babel-runtime@5.8.34/core-js/object/keys.js",
      "npm:core-js@1.2.6/library/fn/object/keys.js",
      "npm:core-js@1.2.6/library/modules/es6.object.keys.js",
      "npm:react-bootstrap@0.28.1/lib/utils/bootstrapUtils.js",
      "npm:react-bootstrap@0.28.1/lib/Tooltip.js",
      "npm:react-prop-types@0.3.0/lib/isRequiredForA11y.js",
      "npm:react-bootstrap@0.28.1/lib/Thumbnail.js",
      "npm:react-bootstrap@0.28.1/lib/SafeAnchor.js",
      "npm:react-bootstrap@0.28.1/lib/Tabs.js",
      "npm:react-bootstrap@0.28.1/lib/utils/ValidComponentChildren.js",
      "npm:keycode@2.1.0.js",
      "npm:keycode@2.1.0/index.js",
      "npm:react-bootstrap@0.28.1/lib/NavItem.js",
      "npm:babel-runtime@5.8.34/helpers/object-without-properties.js",
      "npm:react-bootstrap@0.28.1/lib/Nav.js",
      "npm:react-prop-types@0.3.0/lib/all.js",
      "npm:react-bootstrap@0.28.1/lib/Col.js",
      "npm:react-prop-types@0.3.0/lib/elementType.js",
      "npm:react-prop-types@0.3.0/lib/common.js",
      "npm:react-bootstrap@0.28.1/lib/Table.js",
      "npm:react-bootstrap@0.28.1/lib/Tab.js",
      "npm:react-bootstrap@0.28.1/lib/utils/TransitionEvents.js",
      "npm:react-bootstrap@0.28.1/lib/SplitButton.js",
      "npm:lodash-compat@3.10.1/object/pick.js",
      "npm:lodash-compat@3.10.1/function/restParam.js",
      "npm:lodash-compat@3.10.1/internal/pickByCallback.js",
      "npm:lodash-compat@3.10.1/internal/baseForIn.js",
      "npm:lodash-compat@3.10.1/object/keysIn.js",
      "npm:lodash-compat@3.10.1/support.js",
      "npm:lodash-compat@3.10.1/lang/isString.js",
      "npm:lodash-compat@3.10.1/internal/isObjectLike.js",
      "npm:lodash-compat@3.10.1/lang/isObject.js",
      "npm:lodash-compat@3.10.1/internal/isLength.js",
      "npm:lodash-compat@3.10.1/internal/isIndex.js",
      "npm:lodash-compat@3.10.1/lang/isFunction.js",
      "npm:lodash-compat@3.10.1/lang/isArray.js",
      "npm:lodash-compat@3.10.1/internal/getNative.js",
      "npm:lodash-compat@3.10.1/lang/isNative.js",
      "npm:lodash-compat@3.10.1/internal/isHostObject.js",
      "npm:lodash-compat@3.10.1/lang/isArguments.js",
      "npm:lodash-compat@3.10.1/internal/isArrayLike.js",
      "npm:lodash-compat@3.10.1/internal/getLength.js",
      "npm:lodash-compat@3.10.1/internal/baseProperty.js",
      "npm:lodash-compat@3.10.1/internal/toObject.js",
      "npm:lodash-compat@3.10.1/internal/arrayEach.js",
      "npm:lodash-compat@3.10.1/internal/baseFor.js",
      "npm:lodash-compat@3.10.1/internal/createBaseFor.js",
      "npm:lodash-compat@3.10.1/internal/pickByArray.js",
      "npm:lodash-compat@3.10.1/internal/bindCallback.js",
      "npm:lodash-compat@3.10.1/utility/identity.js",
      "npm:lodash-compat@3.10.1/internal/baseFlatten.js",
      "npm:lodash-compat@3.10.1/internal/arrayPush.js",
      "npm:lodash-compat@3.10.1/object/omit.js",
      "npm:lodash-compat@3.10.1/internal/baseDifference.js",
      "npm:lodash-compat@3.10.1/internal/createCache.js",
      "npm:lodash-compat@3.10.1/internal/SetCache.js",
      "npm:lodash-compat@3.10.1/internal/cachePush.js",
      "npm:lodash-compat@3.10.1/internal/cacheIndexOf.js",
      "npm:lodash-compat@3.10.1/internal/baseIndexOf.js",
      "npm:lodash-compat@3.10.1/internal/indexOfNaN.js",
      "npm:lodash-compat@3.10.1/internal/arrayMap.js",
      "npm:react-bootstrap@0.28.1/lib/SplitToggle.js",
      "npm:react-bootstrap@0.28.1/lib/DropdownToggle.js",
      "npm:react-bootstrap@0.28.1/lib/Button.js",
      "npm:react-bootstrap@0.28.1/lib/Dropdown.js",
      "npm:react-bootstrap@0.28.1/lib/utils/CustomPropTypes.js",
      "npm:react-bootstrap@0.28.1/lib/utils/childrenToArray.js",
      "npm:react-bootstrap@0.28.1/lib/DropdownMenu.js",
      "npm:react-overlays@0.5.4/lib/RootCloseWrapper.js",
      "npm:react-overlays@0.5.4/lib/utils/ownerDocument.js",
      "npm:dom-helpers@2.4.0/ownerDocument.js",
      "npm:react-overlays@0.5.4/lib/utils/createChainedFunction.js",
      "npm:react-overlays@0.5.4/lib/utils/addEventListener.js",
      "npm:dom-helpers@2.4.0/events/off.js",
      "npm:react-bootstrap@0.28.1/lib/ButtonGroup.js",
      "npm:uncontrollable@3.1.4.js",
      "npm:uncontrollable@3.1.4/index.js",
      "npm:uncontrollable@3.1.4/createUncontrollable.js",
      "npm:uncontrollable@3.1.4/utils.js",
      "npm:lodash-compat@3.10.1/collection/find.js",
      "npm:lodash-compat@3.10.1/internal/createFind.js",
      "npm:lodash-compat@3.10.1/internal/baseFindIndex.js",
      "npm:lodash-compat@3.10.1/internal/baseFind.js",
      "npm:lodash-compat@3.10.1/internal/baseCallback.js",
      "npm:lodash-compat@3.10.1/utility/property.js",
      "npm:lodash-compat@3.10.1/internal/isKey.js",
      "npm:lodash-compat@3.10.1/internal/basePropertyDeep.js",
      "npm:lodash-compat@3.10.1/internal/toPath.js",
      "npm:lodash-compat@3.10.1/internal/baseToString.js",
      "npm:lodash-compat@3.10.1/internal/baseGet.js",
      "npm:lodash-compat@3.10.1/internal/baseMatchesProperty.js",
      "npm:lodash-compat@3.10.1/array/last.js",
      "npm:lodash-compat@3.10.1/internal/isStrictComparable.js",
      "npm:lodash-compat@3.10.1/internal/baseSlice.js",
      "npm:lodash-compat@3.10.1/internal/baseIsEqual.js",
      "npm:lodash-compat@3.10.1/internal/baseIsEqualDeep.js",
      "npm:lodash-compat@3.10.1/lang/isTypedArray.js",
      "npm:lodash-compat@3.10.1/internal/equalObjects.js",
      "npm:lodash-compat@3.10.1/object/keys.js",
      "npm:lodash-compat@3.10.1/internal/shimKeys.js",
      "npm:lodash-compat@3.10.1/internal/equalByTag.js",
      "npm:lodash-compat@3.10.1/internal/equalArrays.js",
      "npm:lodash-compat@3.10.1/internal/arraySome.js",
      "npm:lodash-compat@3.10.1/internal/baseMatches.js",
      "npm:lodash-compat@3.10.1/internal/getMatchData.js",
      "npm:lodash-compat@3.10.1/object/pairs.js",
      "npm:lodash-compat@3.10.1/internal/baseIsMatch.js",
      "npm:lodash-compat@3.10.1/internal/baseEach.js",
      "npm:lodash-compat@3.10.1/internal/createBaseEach.js",
      "npm:lodash-compat@3.10.1/internal/baseForOwn.js",
      "npm:dom-helpers@2.4.0/query/contains.js",
      "npm:dom-helpers@2.4.0/activeElement.js",
      "npm:react-bootstrap@0.28.1/lib/Row.js",
      "npm:react-bootstrap@0.28.1/lib/ResponsiveEmbed.js",
      "npm:react-bootstrap@0.28.1/lib/ProgressBar.js",
      "npm:react-bootstrap@0.28.1/lib/Interpolate.js",
      "npm:react-bootstrap@0.28.1/lib/Popover.js",
      "npm:react-bootstrap@0.28.1/lib/PanelGroup.js",
      "npm:react-bootstrap@0.28.1/lib/Panel.js",
      "npm:react-bootstrap@0.28.1/lib/Pagination.js",
      "npm:react-bootstrap@0.28.1/lib/PaginationButton.js",
      "npm:react-bootstrap@0.28.1/lib/utils/createSelectedEvent.js",
      "npm:react-bootstrap@0.28.1/lib/Pager.js",
      "npm:react-bootstrap@0.28.1/lib/PageItem.js",
      "npm:react-bootstrap@0.28.1/lib/PageHeader.js",
      "npm:react-bootstrap@0.28.1/lib/OverlayTrigger.js",
      "npm:react-bootstrap@0.28.1/lib/Overlay.js",
      "npm:react-overlays@0.5.4/lib/Overlay.js",
      "npm:react-prop-types@0.2.2/lib/elementType.js",
      "npm:react-prop-types@0.2.2/lib/common.js",
      "npm:react-overlays@0.5.4/lib/Position.js",
      "npm:react-prop-types@0.2.2/lib/mountable.js",
      "npm:react-overlays@0.5.4/lib/utils/overlayPositionUtils.js",
      "npm:dom-helpers@2.4.0/query/scrollTop.js",
      "npm:dom-helpers@2.4.0/query/isWindow.js",
      "npm:dom-helpers@2.4.0/query/position.js",
      "npm:dom-helpers@2.4.0/query/scrollLeft.js",
      "npm:dom-helpers@2.4.0/query/offsetParent.js",
      "npm:dom-helpers@2.4.0/query/offset.js",
      "npm:react-overlays@0.5.4/lib/utils/getContainer.js",
      "npm:react-overlays@0.5.4/lib/Portal.js",
      "npm:react-bootstrap@0.28.1/lib/NavDropdown.js",
      "npm:react-bootstrap@0.28.1/lib/NavbarBrand.js",
      "npm:react-bootstrap@0.28.1/lib/NavBrand.js",
      "npm:react-bootstrap@0.28.1/lib/utils/deprecationWarning.js",
      "npm:react-bootstrap@0.28.1/lib/Navbar.js",
      "npm:react-bootstrap@0.28.1/lib/NavbarCollapse.js",
      "npm:react-bootstrap@0.28.1/lib/NavbarToggle.js",
      "npm:react-bootstrap@0.28.1/lib/NavbarHeader.js",
      "npm:react-bootstrap@0.28.1/lib/deprecated/Navbar.js",
      "npm:react-bootstrap@0.28.1/lib/Grid.js",
      "npm:react-bootstrap@0.28.1/lib/ModalTitle.js",
      "npm:react-bootstrap@0.28.1/lib/ModalHeader.js",
      "npm:react-bootstrap@0.28.1/lib/ModalFooter.js",
      "npm:react-bootstrap@0.28.1/lib/ModalBody.js",
      "npm:react-bootstrap@0.28.1/lib/Modal.js",
      "npm:react-overlays@0.5.4/lib/utils/isOverflowing.js",
      "npm:react-overlays@0.5.4/lib/Modal.js",
      "npm:react-overlays@0.5.4/lib/utils/addFocusListener.js",
      "npm:react-overlays@0.5.4/lib/ModalManager.js",
      "npm:react-overlays@0.5.4/lib/utils/manageAriaHidden.js",
      "npm:dom-helpers@2.4.0/util/scrollbarSize.js",
      "npm:dom-helpers@2.4.0/class.js",
      "npm:dom-helpers@2.4.0/class/index.js",
      "npm:dom-helpers@2.4.0/class/hasClass.js",
      "npm:dom-helpers@2.4.0/class/removeClass.js",
      "npm:dom-helpers@2.4.0/class/addClass.js",
      "npm:react-bootstrap@0.28.1/lib/ModalDialog.js",
      "npm:dom-helpers@2.4.0/events.js",
      "npm:dom-helpers@2.4.0/events/index.js",
      "npm:dom-helpers@2.4.0/events/filter.js",
      "npm:dom-helpers@2.4.0/query/querySelectorAll.js",
      "npm:react-bootstrap@0.28.1/lib/MenuItem.js",
      "npm:react-bootstrap@0.28.1/lib/ListGroupItem.js",
      "npm:react-bootstrap@0.28.1/lib/ListGroup.js",
      "npm:react-bootstrap@0.28.1/lib/Label.js",
      "npm:react-bootstrap@0.28.1/lib/Jumbotron.js",
      "npm:react-bootstrap@0.28.1/lib/Input.js",
      "npm:babel-runtime@5.8.34/helpers/interop-require-wildcard.js",
      "npm:react-bootstrap@0.28.1/lib/Image.js",
      "npm:react-bootstrap@0.28.1/lib/DropdownButton.js",
      "npm:react-bootstrap@0.28.1/lib/CollapsibleNav.js",
      "npm:react-bootstrap@0.28.1/lib/CarouselItem.js",
      "npm:react-bootstrap@0.28.1/lib/Carousel.js",
      "npm:react-bootstrap@0.28.1/lib/ButtonToolbar.js",
      "npm:react-bootstrap@0.28.1/lib/ButtonInput.js",
      "npm:react-bootstrap@0.28.1/lib/BreadcrumbItem.js",
      "npm:react-bootstrap@0.28.1/lib/Breadcrumb.js",
      "npm:react-bootstrap@0.28.1/lib/Badge.js",
      "npm:react-bootstrap@0.28.1/lib/Alert.js",
      "npm:react-bootstrap@0.28.1/lib/Accordion.js",
      "components/acme_nav_bar/acme-nav-bar.js"
    ]
  },

  map: {
    "babel": "npm:babel-core@5.8.34",
    "babel-runtime": "npm:babel-runtime@5.8.34",
    "classnames": "npm:classnames@2.2.1",
    "clean-css": "npm:clean-css@3.4.8",
    "core-js": "npm:core-js@1.2.6",
    "css": "github:systemjs/plugin-css@0.1.20",
    "react": "npm:react@0.14.3",
    "react-bootstrap": "npm:react-bootstrap@0.28.1",
    "react-dom": "npm:react-dom@0.14.3",
    "react-router": "npm:react-router@1.0.1",
    "react-router-bootstrap": "npm:react-router-bootstrap@0.19.3",
    "scss": "github:mobilexag/plugin-sass@0.1.0",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.5.3"
    },
    "github:jspm/nodelibs-constants@0.1.0": {
      "constants-browserify": "npm:constants-browserify@0.0.1"
    },
    "github:jspm/nodelibs-crypto@0.1.0": {
      "crypto-browserify": "npm:crypto-browserify@3.11.0"
    },
    "github:jspm/nodelibs-domain@0.1.0": {
      "domain-browser": "npm:domain-browser@1.1.4"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-http@1.7.1": {
      "Base64": "npm:Base64@0.2.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-https@0.1.0": {
      "https-browserify": "npm:https-browserify@0.0.0"
    },
    "github:jspm/nodelibs-os@0.1.0": {
      "os-browserify": "npm:os-browserify@0.1.2"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.2"
    },
    "github:jspm/nodelibs-querystring@0.1.0": {
      "querystring": "npm:querystring@0.2.0"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-string_decoder@0.1.0": {
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "github:jspm/nodelibs-url@0.1.0": {
      "url": "npm:url@0.10.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "github:mobilexag/plugin-sass@0.1.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "querystring": "github:jspm/nodelibs-querystring@0.1.0",
      "reqwest": "github:ded/reqwest@2.0.5",
      "sass.js": "npm:sass.js@0.9.4",
      "url": "github:jspm/nodelibs-url@0.1.0"
    },
    "npm:amdefine@1.0.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "module": "github:jspm/nodelibs-module@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:asap@2.0.3": {
      "domain": "github:jspm/nodelibs-domain@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:asn1.js@4.2.1": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "bn.js": "npm:bn.js@4.5.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:babel-runtime@5.8.34": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:browserify-aes@1.0.5": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "buffer-xor": "npm:buffer-xor@1.0.3",
      "cipher-base": "npm:cipher-base@1.0.2",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:browserify-cipher@1.0.0": {
      "browserify-aes": "npm:browserify-aes@1.0.5",
      "browserify-des": "npm:browserify-des@1.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0"
    },
    "npm:browserify-des@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "des.js": "npm:des.js@1.0.0",
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:browserify-rsa@4.0.0": {
      "bn.js": "npm:bn.js@4.5.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "constants": "github:jspm/nodelibs-constants@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "randombytes": "npm:randombytes@2.0.1"
    },
    "npm:browserify-sign@4.0.0": {
      "bn.js": "npm:bn.js@4.5.0",
      "browserify-rsa": "npm:browserify-rsa@4.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.0.2",
      "inherits": "npm:inherits@2.0.1",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:buffer-xor@1.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:buffer@3.5.3": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "is-array": "npm:is-array@1.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:cipher-base@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0"
    },
    "npm:classnames@2.2.1": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:clean-css@3.4.8": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "commander": "npm:commander@2.8.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "https": "github:jspm/nodelibs-https@0.1.0",
      "os": "github:jspm/nodelibs-os@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "source-map": "npm:source-map@0.4.4",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:commander@2.8.1": {
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "graceful-readlink": "npm:graceful-readlink@1.0.1",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:constants-browserify@0.0.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-js@1.2.6": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:create-ecdh@4.0.0": {
      "bn.js": "npm:bn.js@4.5.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.0.2"
    },
    "npm:create-hash@1.1.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "ripemd160": "npm:ripemd160@1.0.1",
      "sha.js": "npm:sha.js@2.4.4"
    },
    "npm:create-hmac@1.1.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:crypto-browserify@3.11.0": {
      "browserify-cipher": "npm:browserify-cipher@1.0.0",
      "browserify-sign": "npm:browserify-sign@4.0.0",
      "create-ecdh": "npm:create-ecdh@4.0.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "diffie-hellman": "npm:diffie-hellman@5.0.0",
      "inherits": "npm:inherits@2.0.1",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "public-encrypt": "npm:public-encrypt@4.0.0",
      "randombytes": "npm:randombytes@2.0.1"
    },
    "npm:des.js@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0"
    },
    "npm:diffie-hellman@5.0.0": {
      "bn.js": "npm:bn.js@4.5.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "miller-rabin": "npm:miller-rabin@4.0.0",
      "randombytes": "npm:randombytes@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:domain-browser@1.1.4": {
      "events": "github:jspm/nodelibs-events@0.1.1"
    },
    "npm:elliptic@6.0.2": {
      "bn.js": "npm:bn.js@4.5.0",
      "brorand": "npm:brorand@1.0.5",
      "hash.js": "npm:hash.js@1.0.3",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:envify@3.4.0": {
      "jstransform": "npm:jstransform@10.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "through": "npm:through@2.3.8"
    },
    "npm:esprima-fb@13001.1001.0-dev-harmony-fb": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:evp_bytestokey@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0"
    },
    "npm:fbjs@0.3.2": {
      "core-js": "npm:core-js@1.2.6",
      "loose-envify": "npm:loose-envify@1.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "promise": "npm:promise@7.0.4",
      "ua-parser-js": "npm:ua-parser-js@0.7.9",
      "whatwg-fetch": "npm:whatwg-fetch@0.9.0"
    },
    "npm:graceful-readlink@1.0.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2"
    },
    "npm:hash.js@1.0.3": {
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:history@1.13.1": {
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "deep-equal": "npm:deep-equal@1.0.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "invariant": "npm:invariant@2.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "qs": "npm:qs@4.0.0",
      "warning": "npm:warning@2.1.0"
    },
    "npm:https-browserify@0.0.0": {
      "http": "github:jspm/nodelibs-http@1.7.1"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:invariant@2.2.0": {
      "loose-envify": "npm:loose-envify@1.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:jstransform@10.1.0": {
      "base62": "npm:base62@0.1.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "esprima-fb": "npm:esprima-fb@13001.1001.0-dev-harmony-fb",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "source-map": "npm:source-map@0.1.31"
    },
    "npm:lodash-compat@3.10.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:loose-envify@1.1.0": {
      "js-tokens": "npm:js-tokens@1.0.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:miller-rabin@4.0.0": {
      "bn.js": "npm:bn.js@4.5.0",
      "brorand": "npm:brorand@1.0.5"
    },
    "npm:os-browserify@0.1.2": {
      "os": "github:jspm/nodelibs-os@0.1.0"
    },
    "npm:parse-asn1@5.0.0": {
      "asn1.js": "npm:asn1.js@4.2.1",
      "browserify-aes": "npm:browserify-aes@1.0.5",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:pbkdf2@3.0.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:process@0.11.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:promise@7.0.4": {
      "asap": "npm:asap@2.0.3",
      "fs": "github:jspm/nodelibs-fs@0.1.2"
    },
    "npm:public-encrypt@4.0.0": {
      "bn.js": "npm:bn.js@4.5.0",
      "browserify-rsa": "npm:browserify-rsa@4.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "randombytes": "npm:randombytes@2.0.1"
    },
    "npm:punycode@1.3.2": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:randombytes@2.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:react-bootstrap@0.28.1": {
      "babel-runtime": "npm:babel-runtime@5.8.34",
      "classnames": "npm:classnames@2.2.1",
      "dom-helpers": "npm:dom-helpers@2.4.0",
      "invariant": "npm:invariant@2.2.0",
      "keycode": "npm:keycode@2.1.0",
      "lodash-compat": "npm:lodash-compat@3.10.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "react": "npm:react@0.14.3",
      "react-dom": "npm:react-dom@0.14.3",
      "react-overlays": "npm:react-overlays@0.5.4",
      "react-prop-types": "npm:react-prop-types@0.3.0",
      "uncontrollable": "npm:uncontrollable@3.1.4",
      "warning": "npm:warning@2.1.0"
    },
    "npm:react-dom@0.14.3": {
      "react": "npm:react@0.14.3"
    },
    "npm:react-overlays@0.5.4": {
      "classnames": "npm:classnames@2.2.1",
      "dom-helpers": "npm:dom-helpers@2.4.0",
      "react": "npm:react@0.14.3",
      "react-dom": "npm:react-dom@0.14.3",
      "react-prop-types": "npm:react-prop-types@0.2.2",
      "warning": "npm:warning@2.1.0"
    },
    "npm:react-prop-types@0.2.2": {
      "warning": "npm:warning@2.1.0"
    },
    "npm:react-prop-types@0.3.0": {
      "warning": "npm:warning@2.1.0"
    },
    "npm:react-router-bootstrap@0.19.3": {
      "react": "npm:react@0.14.3",
      "react-router": "npm:react-router@1.0.1"
    },
    "npm:react-router@1.0.1": {
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "history": "npm:history@1.13.1",
      "invariant": "npm:invariant@2.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "warning": "npm:warning@2.1.0"
    },
    "npm:react@0.14.3": {
      "envify": "npm:envify@3.4.0",
      "fbjs": "npm:fbjs@0.3.2",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.13": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:ripemd160@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:sass.js@0.9.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:sha.js@2.4.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:source-map@0.1.31": {
      "amdefine": "npm:amdefine@1.0.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:source-map@0.4.4": {
      "amdefine": "npm:amdefine@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.13"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:through@2.3.8": {
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:ua-parser-js@0.7.9": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:uncontrollable@3.1.4": {
      "invariant": "npm:invariant@2.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "react": "npm:react@0.14.3"
    },
    "npm:url@0.10.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "punycode": "npm:punycode@1.3.2",
      "querystring": "npm:querystring@0.2.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    },
    "npm:warning@2.1.0": {
      "loose-envify": "npm:loose-envify@1.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  }
});
