language: node_js
node_js:
- 0.12.0
- 0.10.0
sudo: false
branches:
  except:
  - /-job-\d+/
  only:
  - master
before_install:
- set -e
- npm i -g codeclimate-test-reporter jspm
install: 
- npm i
- cd templates
- jspm i
script: npm test
after_script:
- echo "TRAVIS_PULL_REQUEST ${TRAVIS_PULL_REQUEST}"
- echo "TRAVIS_BRANCH ${TRAVIS_BRANCH}"
after_success:
env:
  global: