language: node_js
node_js:
- 0.12.0
sudo: false
branches:
  except:
  - /-job-\d+/
  only:
  - master
before_install:
- set -e
- npm i -g codeclimate-test-reporter jspm
install: 
- npm i
- jspm i
script: npm test
after_script:
- echo "TRAVIS_PULL_REQUEST ${TRAVIS_PULL_REQUEST}"
- echo "TRAVIS_BRANCH ${TRAVIS_BRANCH}"
- codeclimate-test-reporter < coverage/**/lcov.info
after_success:
- if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then firebase deploy --token "${FIREBASE_TOKEN}";fi
env:
  global: