guard 'livereload' do
  watch(%r{.+\.(css|js|scss|html|png|jpeg|gif)})

  # watch the server restart to restart browser after
  watch(%r{restart.log})
end


#!/usr/bin/env python
# from livereload.task import Task
#
# Task.add('*.*')
# Task.add('**/*.*')